### ISSUE TITLE
wrong mutlibytes characters in translation_xx.yaml

### ISSUE THREAD

**Issue by nleguen** [amatsuda/i18n_generators#5]
Here is a part of the generated file :

fr:
  activerecord:
    models:
      user: Utilisateur  #g
      bank_account: Compte de la Banque  #g
      billing_contact: Contact de facturation  #g
      debit: "D\xC3\xA9bit"  #g
      debit_payment: "Paiement par d\xC3\xA9bit"  #g

It should be :

fr:
  activerecord:
    models:
      user: Utilisateur  #g
      bank_account: Compte de la Banque  #g
      billing_contact: Contact de facturation  #g
      debit: "Débit"  #g
      debit_payment: "Paiement par débit"  #g

So it's a problème with encoding I guess... yaml files should be utf-8 encoded

**Comment by amatsuda** [comment]
Please reopen if you're still seeing this problem.
